repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
        exclude: test/fixtures/configs/bad.yml
      - id: end-of-file-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.43.0
    hooks:
      - id: golangci-lint
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.3
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/sirosen/check-jsonschema
    rev: "0.9.1"
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.2.7
    hooks:
      - id: gitleaks
