files:
  Export_2_2022:
    cards:
      card1:
        rowSubSetter:
          start: 10
          end: 31
        colMapper:
          date: 0
          description: 1
          credit: 4
          refund: 5
          balance: 6
        dateLayout: "02/01/2006"

classes:
  Eating outside:
    - ^pizza
  Living:
    - for rent

tags:
  Living:
    - Crucial

database:
  uri: mongodb://localhost
